language: go
sudo: required
dist: trusty

go:
  - 1.9.x
  - 1.12.x

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - CGO_ENABLED=0
  matrix:
  - TARGET=amd64
  - TARGET=arm64

matrix:
  fast_finish: true
  include:
    - os: windows
      env: TARGET=amd64
      go: 1.9.x
    - os: windows
      env: TARGET=amd64
      go: 1.12.x

install:
  - go get github.com/mitchellh/cli
  - go get github.com/soniah/gosnmp
 

script:
notifications:
  email: false

git:
depth: 999999
